### ISSUE TITLE
HL7 TX type, obx.5 leading space being trimmed PipeParser

### ISSUE THREAD

**Issue by slartibartfast3000** [nHapiNET/nHapi#103]
2.4 standard states:
"2.9.48	TX - text data  
String data meant for user display (on a terminal or printer).  Such data would not necessarily be left jus-tified since leading spaces may contribute greatly to the clarity of the presentation to the user.  "

Unless I've missed a config option or rule, escape() function in Escape.cs always trims leading and trailing spaces for type TX i.e.  return result.ToString().Trim();

Perhaps it should be changed to only  TrimEnd?

Example OBX...

Before...
`OBX|23|TX|^Report Line 23||     Sample stored as serological investigations on samples taken within||||||C|||201607270920`

After...
`OBX|23|TX|^Report Line 23||Sample stored as serological investigations on samples taken within||||||C|||201607270920`

The XMLParser works fine as it has KeepAsOriginalNodes property which the PipeParser does not have

**Comment by JeremyOne** [comment]
We also would like to use leading spaces to indent report sections and lists. In our tests with longer reports this increases readability significantly.

**Comment by Usualdosage** [comment]
All primitives (FT, ST, etc) are escaped by default. Are there any other primitives that have this requirement? I'd prefer not to have to put in a one-off just for TX.

**Comment by slartibartfast3000** [comment]
Hi,

Not sure what you mean by escaped, this isn’t an escape problem. The library is trimming leading spaces.

Standard 2.5.1

2.A.78 TX - text data

Definition: String data meant for user display (on a terminal or printer). Such data would not necessarily be left justified since leading spaces may contribute greatly to the clarity of the presentation to the user. Because this type of data is intended for display, it may contain certain escape character sequences Chapter 2: Control Page 2-226 Health Level Seven, Version 2.5.1 © 2007. All rights reserved. April 2007. Final Standard. designed to control the display. Escape sequence formatting is defined in Section 2.7 "Use of escape sequences in text fields". Leading spaces should be included. Trailing spaces should be removed.

**Comment by Usualdosage** [comment]
> Not sure what you mean by escaped, this isn’t an escape problem. The library is trimming leading spaces.

You previously said:

> Unless I've missed a config option or rule, escape() function in Escape.cs always trims leading and trailing spaces for type TX i.e. return result.ToString().Trim();

And you are correct, escape() IS trimming leading and trailing spaces (Escape.cs line 187) for all primitive types, including TX. My question was regarding the other primitive types. Should they also ignore trimming, or is TX "special"?

**Comment by milkshakeuk** [comment]
@slartibartfast3000 FYI in case you are interested.
I copied an `Escape` [unit test from hapi](https://github.com/hapifhir/hapi-hl7v2/blob/efca803e58aea1705ba6b28390ad24c4c3b1d3cb/hapi-test/src/test/java/ca/uhn/hl7v2/parser/EscapeTest.java#L136) (though technically it's not really a unit test since its testing multiple layers).
This unit test show that some whitespace at the end of the string is preserved, but when I copied it into nHapi the whitespace is not preserved

```csharp
[Test]
public void TestPreserveFormattingChars()
{
    var msg = new ORU_R01();

    var ft = new FT(msg);
    msg.GetRESPONSE().GetORDER_OBSERVATION().GetOBSERVATION().OBX.ValueType.Value = "FT";
    msg.GetRESPONSE().GetORDER_OBSERVATION().GetOBSERVATION().OBX.GetObservationValue(0).Data = ft;

    ft.Value = "H \\H\\ N \\N\\ ";

    Assert.AreEqual("H \\H\\ N \\N\\ ", ft.Value);
    Assert.AreEqual("H \\H\\ N \\N\\ ", PipeParser.Encode(ft, _encodingCharacters));

    ft.Value = "H \\C00FF\\ N";
    Assert.AreEqual("H \\C00FF\\ N", ft.Value);
    Assert.AreEqual("H \\C00FF\\ N", PipeParser.Encode(ft, _encodingCharacters));
}
```
Unit test result below
```
Expected string length 12 but was 11. Strings differ at index 11.
Expected: "H \\H\\ N \\N\\ "
But was:  "H \\H\\ N \\N\\"
--------------------------^

at NHapi.NUnit.Parser.EscapeTests.TestPreserveFormattingChars() in C:\DEV\nHapi\tests\NHapi.NUnit\Parser\EscapeTests.cs:line 111
```

this is caused by `Escape.cs` [Line 261](https://github.com/nHapiNET/nHapi/blob/f1921984c2edf43574e4bb5b942906f207f0d07b/src/NHapi.Base/Parser/Escape.cs#L261). 
Hapi does not do any trimming inside `Escape.java` so its highly likely nHapi shouldn't be either.
