### ISSUE TITLE
Why DateTime parser doesn't support fraction of the seconds?

### ISSUE THREAD

**Issue by jakubsuchybio** [nHapiNET/nHapi#104]
Hi,
why is it, that the TSComponentOne which formats DateTime into string and back, can't parse it's own format `LongDateTimeFormatWithFactionOfSecond` ?
In this line:
https://github.com/duaneedwards/nHapi/blob/0ea5a3f9e1a864713bc41568aefcd1201dc14644/NHapi20/NHapi.Base/Model/Primitive/TSComponentOne.cs#L282

the `LongDateTimeFormatWithFactionOfSecond` is missing in supported formats for exact parsing.
Thanks.

**Comment by Usualdosage** [comment]
I saw that you tried to add that with PR #102 . Please create a separate PR for this issue and I will review.
