### ISSUE TITLE
ST Data Type splitting value on message sub component delimiter

### ISSUE THREAD

**Issue by kccarter76** [nHapiNET/nHapi#110]
HL7 version 2.3.1

in the XAD datatype the property OtherDesignation is a ST datatype. the value that is being parsed from a message is.

The literal value located in the message where this component is parsed from is this "MONTECITO HEIGHTS   HC & WELLNESS". The value retrieved from the Value Property of the ST Object is "MONTECITO HEIGHTS HC ".

It has been argued from our interface team with this component field being defined as an ST it should not be treating the '&' character as a delimiter but as literal text.

**Comment by SpaceCheeseII** [comment]
Hi don't know if this helps... according to the hl7 spec ...

As & is a delimiter you've declared in MSH.2, it would need to be escaped. You would have to escape it like this ... \& or replace & in the text with the escape sequence \T\ (decoded by nhapi to the sub separator & in MSH.2)

Take a look at 2.10	USE OF ESCAPE SEQUENCES IN TEXT FIELDS - (nb I only have the 2.4 spec to hand so maybe different chapter number in 2.3.1)

so...

MONTECITO HEIGHTS HC & WELLNESS 

would need to be supplied as

MONTECITO HEIGHTS HC \T\ WELLNESS

Hope that Helps

**Comment by kccarter76** [comment]
other HL7 parsing engines like rhapsody will treat all the text that is located in the position for a ST datatype as literal text and escaping the & was not necessary. It sounds like nhapi is ignoring the business rules and subdividing fields into components where the HL7 standard does not define component fields.

**Comment by slartibartfast3000** [comment]
Sorry, not familiar with rhapsody. Perhaps there were config settings on the Hl7 processor?

For my reference, I'd be grateful if you could point me to the business rules you're looking at - are these in the HL7 standard? it maybe I'm not understanding the need for not escaping.

Mirth is also splitting ST in XAD on &,  so, I suspect it's generally to do with HAPI libs whether Java or .net?

ps. I had to make my own build because TX type was trimming leading white space, this was quite easy to do.

**Comment by milkshakeuk** [comment]
> other HL7 parsing engines like rhapsody will treat all the text that is located in the position for a ST datatype as literal text and escaping the & was not necessary. It sounds like nhapi is ignoring the business rules and subdividing fields into components where the HL7 standard does not define component fields.

I believe as @SpaceCheeseII has already said this is part of the hl7 standard, unless you can point to the specification which suggests otherwise.

**Comment by milkshakeuk** [comment]
closing for now unless @kccarter76 can point to the specification which suggests there is an issue.
