### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by jakubsuchybio** [nHapiNET/nHapi#111]
I see last merged pull request from @duaneedwards in march of 2017.
There is a lot of bugs that are resolved by unmerged pull requests. But owner nowhere to be found.

@duaneedwards Could you please look at the pull requests and merge them?

I know we can fork, create our own packages... For now I am doing that, but should I?

:)

**Comment by elpacko** [comment]
I guess it is because there is a new standard FHIR. I’ve found the following repo

https://github.com/FirelyTeam/fhir-net-api

**Comment by waleswood** [comment]
> I guess it is because there is a new standard FHIR. I’ve found the following repo
> 
> https://github.com/FirelyTeam/fhir-net-api

Does the project you mentioned support hl7 v2.6?

**Comment by andirapandi** [comment]
Is FHIR supposed to replace current HL7?
I think HL7 3 (the xml thingy) never was adapted widely/at all.
On the other hand, all customers I am aware of still use some flavor of HL7 2.x + custom abominations by the large vendors.
I am reasonably happy with https://github.com/Efferent-Health/HL7-dotnetcore , which is not too compatible though. Seems a little more low level, simple and more forgiving then nhapi. I had so many issues with nhapi I cannot even count them. Not sure whether by wrong usage or it just being too close to the spec - and no one caring about the spec.

**Comment by Usualdosage** [comment]
This repo will still be actively maintained. The core object structure is still widely used by many healthcare companies, so until the HL7 is dead and gone, I'll keep this repo going.
