### ISSUE TITLE
Request to be added to the organisation

### ISSUE THREAD

**Issue by milkshakeuk** [nHapiNET/nHapi#115]
Hi @duaneedwards I would like to be added to the organisation, not to become the maintainer of nhapi but I would at least try to help modernise the library for use with dotnet core and beyond.

**Comment by duaneedwards** [comment]
Thanks Jake, invitation should be sent now.

If you run into any permissions issues trying to push your work just let me know and I can adjust if necessary.

I think it might be a good idea bump the version number to start with 3 with such changes as migrating to dotnet core is possibly a breaking change for consumers of the existing libraries.

**Comment by milkshakeuk** [comment]
@duaneedwards in regards to the hl7 database that is used to generate the c# classes is this something you can share if not how would I go about obtaining or at least using a copy in a ci/cd pipeline to ensure everything still works as expected.

**Comment by milkshakeuk** [comment]
> I think it might be a good idea bump the version number to start with 3 with such changes as migrating to dotnet core is possibly a breaking change for consumers of the existing libraries.

@duaneedwards I am considering targeting net35 in addition to netstandard, that will mean it should work for existing consumers but at the same time enables netstandard support as well.

If I make that change then technically all I would be doing is targeting an additional framework. There would be no functional changes and the generated classes will remain identical, so not sure there would need to be a Major version bump at that point.

If you feel it would still be advantageous to bump the Major version then it shall be done since I am not wholly against it.

**Comment by milkshakeuk** [comment]
> @duaneedwards in regards to the hl7 database that is used to generate the c# classes is this something you can share if not how would I go about obtaining or at least using a copy in a ci/cd pipeline to ensure everything still works as expected.

@duaneedwards is this something you can help with?

**Comment by ryankelley** [comment]
@duaneedwards I would also like to be added. I have had some issues and PR's open for months, and we actively use this in several production scenarios. Being able to contribute and give back would be great.

**Comment by duaneedwards** [comment]
@milkshakeuk Sorry but I can't help you sourcing the hl7 database as that's a licensed product you'd need to purchase from HL7.org.  If I recall correctly it was a couple thousand USD so it's a pretty limiting factor for working with this project.

@ryankelley I've just invited you now with write access, let me know if you need further permissions.

FYI I don't have much time to put towards this project for the foreseeable future, but will try and help if possible.

**Comment by milkshakeuk** [comment]
@duaneedwards from what I can tell, although I have access to the repo I dont seem to be in the organisation.
https://github.com/orgs/nHapiNET/people
does that matter?

**Comment by milkshakeuk** [comment]
@duaneedwards thanks, that seemed to have worked, did you get my email I sent to hl7.org?

**Comment by milkshakeuk** [comment]
@ryankelley did you accept the invite?
