### ISSUE TITLE
Reset all master back to before the PR's were merged

### ISSUE THREAD

**Issue by milkshakeuk** [nHapiNET/nHapi#122]
@Usualdosage I think we should reset master back to https://github.com/nHapiNET/nHapi/commit/4b197978f81d4010e777151d95b2089a2b93dc2a and re-open all the pull requests then we won't pollute the git log history with lots of revert commits.

Once this is done, we can come up with a strategy in regards to what order we want to deal with the PR.

If you are ok with this let me know and I'll do it using git cli.

P.S. I have pushed my latest changes to the netstandard2.0 PR to add back support to .netframework3.5, the changes are [here](https://github.com/nHapiNET/nHapi/pull/112/commits/7fcaf87e16204a17b5be2672a71ab65ccf1176de) to review, but still we should wait until it's been tested with the normative database before we complete any merge since this will be a major change.

**Comment by Usualdosage** [comment]
@milkshakeuk I don't agree. The development of this repo has been halted for a long time. We can't count on getting a copy of the Normative DB in the near future. All of the changes were to the connection (OLE vs ODBC) and code-wise I see zero problem with that. Let's push forward. If we break, we revert. But I don't want to stall out.

**Comment by milkshakeuk** [comment]
@Usualdosage it may have halted in the past, but now there are active contributers it shouldn't be an issue any more, plus that's not an excuse to not revert the re review the pull requests.

 Since now there is a better understanding of how NHapi was designed but with code generation in mind we can put a bit more time and care into the review of the PRs and ask for tests ect where needed.

Also as a side node those existing merges have caused a merge conflict for my pull request, that's not a problem at the very least you may want the first chance to be to support netstandard.

**Comment by Usualdosage** [comment]
Ok. I'm fine with re-reviewing the PRs, as long as they are done in a timely fashion. Getting the netstandard support out the door is my top priority.

**Comment by milkshakeuk** [comment]
@Usualdosage I have reverted repository back to the commit, and pushed what was master to a new branch called [master-backup](https://github.com/nHapiNET/nHapi/tree/master-backup) so we can cherry pick any previously merged pull requests back into master as and when we have reviewed them.

Unfortunately, there is no way to re-open a historically merged PR on GitHub, the person that originally created it would have to create it again which is why I created the [master-backup](https://github.com/nHapiNET/nHapi/tree/master-backup) branch
