### ISSUE TITLE
Parsing ADT_A39 v2.3 message fails

### ISSUE THREAD

**Issue by NieminenS** [nHapiNET/nHapi#131]
MSH|^~\&|HKT|PSHP|XARCHIVE|PSHP|20210111060512||ADT^A39|000000026894447|P|2.3|||AL|NE||8859/1
EVN|A39|20210111060512
PID||110121xxxxx^^^PSHP^HETU|110121xxxxx^^^PSHP^HETU||NN^NN^^^^^D^A||20210111|1|^""^^^^^A^A~""^^^^^^M^A||xxxx^^837 xxxx^^33400 xxxx^""^M||^PRN^PH^^^^0442062007|^WPN^PH^^^^""|fi||||||280887-114M^^^PSHP^HETU|||||||""|""|N||""
MRG|110121A025^^^PSHP^VHETU|||110121A025^^^PSHP^VHETU

The parser returns "Error while parsing: PID does not exist in the group NHapi.Model.V23.Message.ADT_A39".

I use HAPI test panel for sending messages. I have checked that there no non-printable characters in the message.

**Comment by milkshakeuk** [comment]
Hi @NieminenS can you give me a bit more detail? How are you trying to access the PID?
I wrote this test and it passes just fine.

```c#
using System;
using NHapi.Base.Model;
using NHapi.Base.Parser;
using NHapi.Model.V23.Message;
using NHapi.Model.V23.Segment;
using NUnit.Framework;

...

[Test]
public void TestGithubIssue131ADT_A39()
{
    var message = @"MSH|^&|HKT|PSHP|XARCHIVE|PSHP|20210111060512||ADT^A39|000000026894447|P|2.3|||AL|NE||8859/1
EVN|A39|20210111060512
PID||110121xxxxx^^^PSHP^HETU|110121xxxxx^^^PSHP^HETU||NN^NN^^^^^D^A||20210111|1|^""""^^^^^A^A""""^^^^^^M^A||xxxx^^837 xxxx^^33400 xxxx^""""^M||^PRN^PH^^^^0442062007|^WPN^PH^^^^""""|fi||||||280887-114M^^^PSHP^HETU|||||||""""|""""|N||""""
MRG|110121A025^^^PSHP^VHETU|||110121A025^^^PSHP^VHETU";

    var expectedPatientId = "110121xxxxx";

    var parser = new PipeParser();

    var parsed = (ADT_A39) parser.Parse(message);
    var patient = parsed.GetPATIENT();

    var actualPatientId = patient.PID.PatientIDExternalID.ID.Value;

    Assert.AreEqual(expectedPatientId, actualPatientId);
}
```

**Comment by NieminenS** [comment]
Hi,

thank you for the swift response. I am planning to use NHapi in an ongoing customer project and this helps me forward.

The NHapi version installed is 3.0.0-preview.1. However, that is not the issue, but the way how I tried to access the message. An example I found (from "The NHapi Beginner's Guide", 2013) was written as follows:

                        NHapi.Model.V23.Segment.PID pid1 = (NHapi.Model.V23.Segment.PID)hl7Message.GetStructure("PID");
                        Console.WriteLine("PatientID {0}.", pid1.PatientIDExternalID.ID.Value);

This accidentally seems to work for ADT_A31 but not A39, which was further misleading me.

I was able to re-write my sample by using your advice, casting the types correctly, and now it works.

NHapi looks great, the only weakness from a novel user's point of view is sparse and outdated documentation. I try to make better use of the source code to build my understanding. I would also welcome any recommendations from you about useful posts etc.

Best regards,

Seppo

**Comment by milkshakeuk** [comment]
@NieminenS the specification for ADT^39 v2.3 look like this:
https://hl7-definition.caristix.com/v2/HL7v2.3/TriggerEvents/ADT_A39

Where As the specification for ADT^31 v2.3 looks like this:
https://hl7-definition.caristix.com/v2/HL7v2.3/TriggerEvents/ADT_A31

even though the hl7 structure may look similar when you compare the raw message structure, in the A31 `PID` is part of the top-level collection of segments whereas in the A39 `PID` is part of the `PATIENT` component, that's the reason the code for the A31 did not work with the A39.

**Comment by NieminenS** [comment]
@milkshakeuk - thanks, you are right:

<img width="453" alt="ADT_A39_structure" src="https://user-images.githubusercontent.com/1269381/107652955-c9639c80-6c89-11eb-9dee-73de6aed78b2.png">
