### ISSUE TITLE
Fails to parse ADT_A39 v2.3 message

### ISSUE THREAD

**Issue by NieminenS** [nHapiNET/nHapi#132]
MSH|^~\&|HKT|PSHP|XARCHIVE|PSHP|20210111060512||ADT^A39|000000026894447|P|2.3|||AL|NE||8859/1
EVN|A39|20210111060512
PID||110121xxxxx^^^PSHP^HETU|110121xxxxx^^^PSHP^HETU||NN^NN^^^^^D^A||20210111|1|^""^^^^^A^A~""^^^^^^M^A||xxxx^^837 xxxx^^33400 xxxx^""^M||^PRN^PH^^^^0442062007|^WPN^PH^^^^""|fi||||||280887-114M^^^PSHP^HETU|||||||""|""|N||""
MRG|110121A025^^^PSHP^VHETU|||110121A025^^^PSHP^VHETU

The parser returns "Error while parsing: PID does not exist in the group NHapi.Model.V23.Message.ADT_A39".

I use HAPI test panel for sending messages. I have checked that there no non-printable characters in the message.

**Comment by NieminenS** [comment]
Duplicate.

**Comment by milkshakeuk** [comment]
@NieminenS which ticket is this a duplicate of?

**Comment by NieminenS** [comment]
Hi, issuen #131. I amended my comment to issue #132 with this information.  BR Seppo
