### ISSUE TITLE
Add StyleCopAnalyzers to main projects

### ISSUE THREAD

**Issue by AMCN41R** [nHapiNET/nHapi#138]
Add [StyleCopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) nuget package and associated configuration to main projects:
- ModelGenerator
- NHapi.Base
- NHapi.SourceGeneration
- NHapi.NUnit.SourceGeneration

Requierd configuration files:
- stylecop.json
- .editorconfig file
- omnisharp.json (for VS code support)

These files can be stored at the solution level, and refrenced by each project.

Default rules can be found [here...](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/tree/master/documentation)

Linked to #124

**Comment by AMCN41R** [comment]
@milkshakeuk @duaneedwards - if you guys have any specific style preferences, lets document here?

**Comment by milkshakeuk** [comment]
Sounds good to me, I don't have a preference so I would recommend the microsoft standard rules, you can probably obtain an `.editorconfig` from one of their repos.

**Comment by AMCN41R** [comment]
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options

**Comment by milkshakeuk** [comment]
The one thing I would say is that any public members which might clash against the naming rules, should be ignored to begin with this otherwise we will break the API contract.

My plan with this is to have 2 (new correctly styled members) and the old ones remain with `Obsolete` attributes applied. These can be removed in a future major revision.

**Comment by AMCN41R** [comment]
Yep. Agreed.

**Comment by AMCN41R** [comment]
StyleCop.Analyzers has a rule for file headers, [SA1633](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1633.md), that is enabled by default.

![image](https://user-images.githubusercontent.com/15929161/106447706-b971de80-6479-11eb-98ab-9daec60a9a8d.png)

Do you want this in each file? If not, we can globally disable the rule.

I'm happy either way.

**Comment by milkshakeuk** [comment]
I think this one can probably be turned off, unless @duaneedwards has any issues with this.

**Comment by duaneedwards** [comment]
No issues with turning this off from my side

**Comment by AMCN41R** [comment]
https://github.com/nHapiNET/nHapi/pull/143

**Comment by milkshakeuk** [comment]
@AMCN41R I think this is covered by #143 so ill close it.
