### ISSUE TITLE
Repository Settings / Permissions

### ISSUE THREAD

**Issue by milkshakeuk** [nHapiNET/nHapi#139]
Hi @duaneedwards can you give me access to the repository settings tab so I can set up things like issue templates.

I would also like to be able to [publish nuget releases to via github](https://github.com/orgs/nHapiNET/packages?repo_name=nHapi) as well as nuget.org.

This _could_ be used to publish alphas, experimental releases or CI/CD builds before being released to nuget.org, _or_  just an additional location to publish the packages.

Thanks in advance.

**Comment by duaneedwards** [comment]
Have applied the maintainer role to your account, hopefully this gives you what you need.

**Comment by milkshakeuk** [comment]
@duaneedwards I have followed the instructions [here](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#creating-issue-templates) but no joy, I do have the settings tab now with a few options for setting up the types of merges etc but no **features** or **issues** section.

![Screenshot_20210201-194853.png](https://user-images.githubusercontent.com/1087376/106510221-8e61ac00-64c6-11eb-8836-50c4f876220b.png)

**Comment by duaneedwards** [comment]
I can see those options on my account so it must be an admin level feature I guess, have made you admin now so hopefully you can see the Features section now.

**Comment by milkshakeuk** [comment]
@duaneedwards ok that has worked, thank you!
