### ISSUE TITLE
HL7 2.5 OML_O33 Lab Order 

### ISSUE THREAD

**Issue by sadath** [nHapiNET/nHapi#144]
I am using OML_O33 to generate the Lab order 
I  have Created the Message Header Segment with Values 
I want to Add Specimen after pid i am unable to add 
i am finding Issues  adding the specimen below is the sample message 

```
MSH|^~\&|||R|a|20161012144125||OML^033^OML_033|2016101214500200002|P|2.5|||||||UNICODE UTF-8
PID|1||PID0002^^^^PI||Doe^John||19800926|M
SPM|1|0123456789||WB||||||P||||||20161012145110|20161012181002
ORC|NW|||||||||||||||||^Hematology_Department
OBR|1|||CBC||||||||||||789456^Sam
```

```csharp
private void createspcimen()
{
     NHapi.Model.V25.Message.OML_O33 a1 = new NHapi.Model.V25.Message.OML_O33();
} 
```

**Comment by milkshakeuk** [comment]
Hi,

Could you please provide some more information?
What version of NHapi are you using?

What hl7 version are trying to generate a message for?

**Comment by sadath** [comment]
> Hi,
> 
> Could you please provide some more information?
> What version of NHapi are you using?
> 
> What hl7 version are trying to generate a message for?

Thanks for the Reply 


Nhapi version is  2.4.0.0

I am trying to generate for HL7 Messaging Standard 2.5

I am trying write a program for an lab machine  in which with my local data base i have to convert to hl7 format of 2.5 
and then send and  receive the  data from the machine below is sample Message Structure  given by the machine vendor  

MSH|^~\&|||YH5^123456A^1.0.0|MEDICAL|20161012144125||OML^033^OML_033|
2016101214500200002|P|2.5|||||||UNICODE UTF-8
PID|1||PID0002^^^^PI||Doe^John||19800926|M
SPM|1|0123456789||WB||||||P||||||20161012145110|20161012181002
ORC|NW|||||||||||||||||^Hematology_Department
OBR|1|||CBC||||||||||||789456^MISTER PHYSICIAN

**Comment by milkshakeuk** [comment]
Could you provide a code sample of how you have tried to construct this message?

also is there any reason you are using an old version of nhapi?

**Comment by sadath** [comment]
> Could you provide a code sample of how you have tried to construct this message?
> 
> also is there any reason you are using an old version of nhapi?

No reason i can use the latest one 
below is how I am trying to construct 


internal class Message
    {

        private NHapi.Model.V25.Message.OML_O33 a1;
       
        public NHapi.Model.V25.Message.OML_O33 Build()
        {
            var currentDateTimeString = GetCurrentTimeStamp();
            var a1 = new NHapi.Model.V25.Message.OML_O33();

            createoml33(currentDateTimeString);
            createspcimen();
            //CreateObrSegment();




            return a1;
        }

       

        private string GetCurrentTimeStamp()
        {
            return DateTime.Now.ToString("yyyyMMddHHmmss", CultureInfo.InvariantCulture);
        }

        private void createoml33(string currentDateTimeString)
        {
            NHapi.Model.V25.Message.OML_O33 a1 = new NHapi.Model.V25.Message.OML_O33();
            var MESEG = a1.MSH;
            var b1 = a1.GetSPECIMEN();

            MESEG.FieldSeparator.Value = "|";
            MESEG.EncodingCharacters.Value = "^~\\&";
            MESEG.SendingApplication.NamespaceID.Value = "Our System";
            MESEG.SendingFacility.NamespaceID.Value = "Our Facility";
            MESEG.ReceivingApplication.NamespaceID.Value = "Their Remote System";
            MESEG.ReceivingFacility.NamespaceID.Value = "Their Remote Facility";
            // MESEG.DateTimeOfMessage.TimeOfAnEvent.Value = currentDateTimeString;
            //  MESEG.MessageControlID.Value = GetSequenceNumber();
            // MESEG.MessageType.MessageType.Value = "OML_O33";
            MESEG.MessageType.TriggerEvent.Value = "OML_O33";
            // MESEG.VersionID.Value = "2.5";
            MESEG.ProcessingID.ProcessingID.Value = "P";
            //var spm = a1.s();
            //var sppm = a1.();
            b1.SPM.SetIDSPM.Value = "a";

        }
        private void createspcimen()
        {

            NHapi.Model.V25.Message.OML_O33 a1 = new NHapi.Model.V25.Message.OML_O33();
            var asd = a1.GetSPECIMEN().SPM;
            asd.SetIDSPM.Value = "1";




        }

       
    }

**Comment by milkshakeuk** [comment]
Hi, there is a useful web article showing how you can create messages with nHpi [here](https://saravanansubramanian.com/hl72xnhapicreatemessage/).

I used that article as a basis and to create the example hl7 message you described, you would do something like this:
```csharp
using NHapi.Model.V25.Message;
using System;
using System.Globalization;

namespace NHapi.NUnit
{
    public class OmlO33MessageBuilder
    {
        private OML_O33 _omlMessage;

        public OML_O33 Build()
        {
            var currentDateTimeString = GetCurrentTimeStamp();
            _omlMessage = new OML_O33();

            CreateMshSegment(currentDateTimeString);
            CreatePidSegment();
            CreateSpecimen();

            return _omlMessage;
        }

        private void CreateMshSegment(string currentDateTimeString)
        {
            var msh = _omlMessage.MSH;

            msh.FieldSeparator.Value = "|";
            msh.EncodingCharacters.Value = "^~\\&";
            msh.ReceivingApplication.NamespaceID.Value = "R";
            msh.ReceivingFacility.NamespaceID.Value = "a";
            msh.DateTimeOfMessage.Time.Value = currentDateTimeString;
            msh.MessageControlID.Value = GetSequenceNumber();
            msh.MessageType.MessageCode.Value = "OML";
            msh.MessageType.MessageStructure.Value = "OML_033";
            msh.MessageType.TriggerEvent.Value = "O33";
            msh.VersionID.VersionID.Value = "2.5";
            msh.ProcessingID.ProcessingID.Value = "P";
            msh.PrincipalLanguageOfMessage.Identifier.Value = "UNICODE UTF-8";
        }

        private void CreatePidSegment()
        {
            var pid = _omlMessage.PATIENT.PID;

            pid.SetIDPID.Value = "1";
            pid.AdministrativeSex.Value = "M";
            pid.DateTimeOfBirth.Time.Value = "19800926";

            var patientName = pid.GetPatientName(0);

            patientName.FamilyName.Surname.Value = "Doe";
            patientName.GivenName.Value = "John";

            var identifierList = pid.GetPatientIdentifierList(0);

            identifierList.IDNumber.Value = "PID0002";
            identifierList.IdentifierTypeCode.Value = "PI";
        }

        private void CreateSpecimen()
        {
            var specimen = _omlMessage.GetSPECIMEN();
            var spm = specimen.SPM;

            spm.SetIDSPM.Value = "1";
            spm.SpecimenID.PlacerAssignedIdentifier.EntityIdentifier.Value = "0123456789";
            spm.SpecimenType.Identifier.Value = "WB";
            spm.SpecimenCollectionSite.Identifier.Value = "P";
            spm.SpecimenCollectionDateTime.RangeStartDateTime.Time.Value = "20161012181002";

            var riskCode = spm.GetSpecimenRiskCode(0);

            riskCode.Identifier.Value = "20161012145110";

            CreateSpecimenOrder();
        }

        private void CreateSpecimenOrder()
        {
            var order = _omlMessage.GetSPECIMEN().GetORDER(0);
            var orc = order.ORC;

            orc.OrderControl.Value = "NW";
            orc.EnteringDevice.Text.Value = "Hematology_Department";

            var obr = order.OBSERVATION_REQUEST.OBR;

            obr.SetIDOBR.Value = "1";
            obr.UniversalServiceIdentifier.Identifier.Value = "CBC";

            var provider = obr.GetOrderingProvider(0);

            provider.IDNumber.Value = "789456";
            provider.FamilyName.Surname.Value = "Sam";
        }

        private string GetCurrentTimeStamp()
        {
            return DateTime.Now.ToString("yyyyMMddHHmmss", CultureInfo.InvariantCulture);
        }

        private string GetSequenceNumber()
        {
            const string facilityNumberPrefix = "1234"; // some arbitrary prefix for the facility
            return facilityNumberPrefix + GetCurrentTimeStamp();
        }
    }
}
```
and here is how you would use it.
```csharp
var oml_033 = new OmlO33MessageBuilder().Build();

var parser = new PipeParser();

var result = parser.Encode(oml_033);
```
and this was the result.
```
MSH|^~\&|||R|a|20210210194931||OML^O33^OML_033|123420210210194931|P|2.5|||||||UNICODE UTF-8
PID|1||PID0002^^^^PI||Doe^John||19800926|M
SPM|1|0123456789||WB||||||P||||||20161012145110|20161012181002
ORC|NW|||||||||||||||||^Hematology_Department
OBR|1|||CBR||||||||||||789456^Sam
```
Hope this helps!

**Comment by sadath** [comment]
> Hi, there is a useful web article showing how you can create messages with nHpi [here](https://saravanansubramanian.com/hl72xnhapicreatemessage/).
> 
> I used that article as a basis and to create the example hl7 message you described in your first post, you would do something like this:
> 
> ```cs
> using NHapi.Model.V25.Message;
> using System;
> using System.Globalization;
> 
> namespace NHapi.NUnit
> {
>     public class OmlO33MessageBuilder
>     {
>         private OML_O33 _omlMessage;
> 
>         public OML_O33 Build()
>         {
>             var currentDateTimeString = GetCurrentTimeStamp();
>             _omlMessage = new OML_O33();
> 
>             CreateMshSegment(currentDateTimeString);
>             CreatePidSegment();
>             CreateSpecimen();
> 
>             return _omlMessage;
>         }
> 
>         private void CreateMshSegment(string currentDateTimeString)
>         {
>             var msh = _omlMessage.MSH;
> 
>             msh.FieldSeparator.Value = "|";
>             msh.EncodingCharacters.Value = "^~\\&";
>             msh.ReceivingApplication.NamespaceID.Value = "R";
>             msh.ReceivingFacility.NamespaceID.Value = "a";
>             msh.DateTimeOfMessage.Time.Value = currentDateTimeString;
>             msh.MessageControlID.Value = GetSequenceNumber();
>             msh.MessageType.MessageCode.Value = "OML";
>             msh.MessageType.MessageStructure.Value = "OML_033";
>             msh.MessageType.TriggerEvent.Value = "O33";
>             msh.VersionID.VersionID.Value = "2.5";
>             msh.ProcessingID.ProcessingID.Value = "P";
>             msh.PrincipalLanguageOfMessage.Identifier.Value = "UNICODE UTF-8";
>         }
> 
>         private void CreatePidSegment()
>         {
>             var pid = _omlMessage.PATIENT.PID;
> 
>             pid.SetIDPID.Value = "1";
>             pid.AdministrativeSex.Value = "M";
>             pid.DateTimeOfBirth.Time.Value = "19800926";
> 
>             var patientName = pid.GetPatientName(0);
> 
>             patientName.FamilyName.Surname.Value = "Doe";
>             patientName.GivenName.Value = "John";
> 
>             var identifierList = pid.GetPatientIdentifierList(0);
> 
>             identifierList.IDNumber.Value = "PID0002";
>             identifierList.IdentifierTypeCode.Value = "PI";
>         }
> 
>         private void CreateSpecimen()
>         {
>             var specimen = _omlMessage.GetSPECIMEN();
>             var spm = specimen.SPM;
> 
>             spm.SetIDSPM.Value = "1";
>             spm.SpecimenID.PlacerAssignedIdentifier.EntityIdentifier.Value = "0123456789";
>             spm.SpecimenType.Identifier.Value = "WB";
>             spm.SpecimenCollectionSite.Identifier.Value = "P";
>             spm.SpecimenCollectionDateTime.RangeStartDateTime.Time.Value = "20161012181002";
> 
>             var riskCode = spm.GetSpecimenRiskCode(0);
> 
>             riskCode.Identifier.Value = "20161012145110";
> 
>             CreateSpecimenOrder();
>         }
> 
>         private void CreateSpecimenOrder()
>         {
>             var order = _omlMessage.GetSPECIMEN().GetORDER(0);
>             var orc = order.ORC;
> 
>             orc.OrderControl.Value = "NW";
>             orc.EnteringDevice.Text.Value = "Hematology_Department";
> 
>             var obr = order.OBSERVATION_REQUEST.OBR;
> 
>             obr.SetIDOBR.Value = "1";
>             obr.UniversalServiceIdentifier.Identifier.Value = "CBC";
> 
>             var provider = obr.GetOrderingProvider(0);
> 
>             provider.IDNumber.Value = "789456";
>             provider.FamilyName.Surname.Value = "Sam";
>         }
> 
>         private string GetCurrentTimeStamp()
>         {
>             return DateTime.Now.ToString("yyyyMMddHHmmss", CultureInfo.InvariantCulture);
>         }
> 
>         private string GetSequenceNumber()
>         {
>             const string facilityNumberPrefix = "1234"; // some arbitrary prefix for the facility
>             return facilityNumberPrefix + GetCurrentTimeStamp();
>         }
>     }
> }
> ```
> 
> and here is how you would use it.
> 
> ```cs
> var oml_033 = new OmlO33MessageBuilder().Build();
> 
> var parser = new PipeParser();
> 
> var result = parser.Encode(oml_033);
> ```
> 
> and this was the result.
> 
> ```
> MSH|^~\&|||R|a|20210210194931||OML^O33^OML_033|123420210210194931|P|2.5|||||||UNICODE UTF-8
> PID|1||PID0002^^^^PI||Doe^John||19800926|M
> SPM|1|0123456789||WB||||||P||||||20161012145110|20161012181002
> ORC|NW|||||||||||||||||^Hematology_Department
> OBR|1|||CBR||||||||||||789456^Sam
> ```
> 
> Hope this helps!
> 
> If you wan't to generate yoru second example you will need to tweek it slightly.

thank you so very much its very helpful thanks a lot

**Comment by milkshakeuk** [comment]
@sadath no problem, I'll close this issue, reopen if there is an issue with NHapi.

**Comment by sadath** [comment]
It was very Helpfull
