### ISSUE TITLE
Register package id prefix

### ISSUE THREAD

**Issue by milkshakeuk** [nHapiNET/nHapi#189]
It is [recommended by Microsoft](https://docs.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices#types-of-recommendations) to reserve and therefore protect the nuget package id by using a registered prefix.

>✔️ CONSIDER choosing a NuGet package name with a prefix that meets NuGet's prefix reservation criteria.

You can register a prefix following these [instructions](https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation#id-prefix-reservation-application-process).

This would indicate that the nHapi package is the original NHapi package with an icon, plus any future complimentary packages we might consider in the future such as adding dependency injection support for modern dotnet applications.

@duaneedwards is this something you can sort out?

**Comment by milkshakeuk** [comment]
@duaneedwards Ok I followed the process and was able to register the prefix, see response below, the only slight issue is that the prefix registered is `nHapi.*` where as all our namespaces are `NHapi.*` I'm not sure if that is a problem.

![nuget-email](https://user-images.githubusercontent.com/1087376/122010904-7b83b000-cdb3-11eb-8408-7c4f59a385f1.png)

This means that we can release new nuget packages prefixed with `nHapi.` and get the little blue tick like so:

![image](https://user-images.githubusercontent.com/1087376/122012579-3ceef500-cdb5-11eb-8587-706c791cb104.png)

For example, if we wanted to add new non-core features such as create a package for dependency injection that works with `IServiceCollection`,  apsnetcore MVC middleware to add hl7 support or even if we want to break the nHapi library down into its core components so people can just depend on the parts of nHapi they need rather than taking everything, we could do so as with the new `nHapi.*` prefix and those nuget packages that would be part of the `nHapi` family.

@duaneedwards @AMCN41R 
So `v3.0.0.0` is coming very soon (unless some major bug or issue is found in `v3.0.0-preview.3` which I'm fairly certain won't happen, what do you guys think about offering 2 approaches to consuming nHapi in a given project (at least during in the `V3` era).

1. You continue to download the `nHapi` with all the dlls (~19mb) as it has always been.
2. You download just the packages you need for your use case i.e. `nHapi.Base` and `nHap.Model.V24` for example.

We could do this as part of the `v3.0.0.0` release, let me know what you think or what other ideas you have or if the prefix with the lower case n is an issue.

**Comment by AMCN41R** [comment]
I think its sensible to break down the packages - as long as we leave the full one too, and make it clear in the docs what packages you need to download.

I dont think the casing of nHapi will matter - using your example, `xunit` is lowercase, but the default namespace is `Xunit`

**Comment by duaneedwards** [comment]
Agree on both counts to what AMCN41R said.  Definitely would want to keep the full package with all versions.

I could see some confusion by users if they just downloaded a specific version package and messages failed to parse due to missing DLLs.  If it comes up, at that point may need to provide guidance / documentation around that to point them to.

**Comment by milkshakeuk** [comment]
@duaneedwards Thanks for getting back to us, I agree of course.

I plan on doing the release sometime week after next (since I am unavailable next week), but before I do, I would like to update the wiki and the readme to make it super clear.

@duaneedwards did you receive me email btw?

**Comment by duaneedwards** [comment]
Sounds good, got the email and am just catching up on things now ... a bit under the pump now with various projects so may take some time to respond in general.

**Comment by milkshakeuk** [comment]
![Screenshot_20210622-193923.png](https://user-images.githubusercontent.com/1087376/122981436-a82a5f80-d391-11eb-97db-78717d4bccaa.png)

Will close this issue now.
