### ISSUE TITLE
NHAPI.Model.V24 not strongly named

### ISSUE THREAD

**Issue by Talcon2** [nHapiNET/nHapi#227]
When trying to compile an application with NHAPI.Model.V24 referenced, visual studio throws an error:
assembly 'NHapi.Base, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
 A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

**Comment by milkshakeuk** [comment]
@Talcon2 thanks ill look into this.

**Comment by milkshakeuk** [comment]
@Talcon2 could you check with version 3.0.2 and let me know how that goes?

**Comment by milkshakeuk** [comment]
@Talcon2 I'm closing date this, as I believe I have released a fix in version 3.0.2.

If you feel it's still an issue please feel free to re-open this issue.
