### ISSUE TITLE
V2.8 ORU_R40

### ISSUE THREAD

**Issue by alberk8** [nHapiNET/nHapi#231]
**Describe the bug**
I have a ORU_R40 which is an Alarm message but the library is missing the R40 message.

**To Reproduce**
Steps to reproduce the behaviour, include sample code whenever possible

```
MSH|^~\&|MINDRAY_VS900^00A03700980057A1^EUI-64||||20210905161256||ORU^R40^ORU_R40|38|P|2.6|||AL|NE||UNICODE UTF-8|||IHE_PCD_ACM_001^IHE PCD^1.3.6.1.4.1.19376.1.6.1.4.1^ISO
PID|||@609331@^^^Hospital^PI||^^^^^^L||||||||||||||||||||||||||||||^Name
PV1||||||||||||||||||||||||||||||||||||||||||||20210905
OBR|1||38^MINDRAY_VS900^00A03700980057A1^EUI-64|196616^MDC_EVT_ALARM^MDC|||20210905161256||||||||||||||||||||||^38&MINDRAY_VS900&00A03700980057A1&EUI-64
OBX|1|CWE|196616^MDC_EVT_ALARM^MDC|1.3.1.202834.1|202834^MDC_EVT_STAT_OFF^MDC||||||F|||20210905161256
OBX|2|CWE|68164^MDC_ATTR_ALERT_SOURCE^MDC|1.3.1.202834.2|69953^MDC_DEV_MON_PT_PHYSIO_MULTI_PARAM_MDS^MDC||||||F
OBX|3|ST|68165^MDC_ATTR_EVENT_PHASE^MDC|1.3.1.202834.3|start||||||F
OBX|4|ST|68166^MDC_ATTR_ALARM_STATE^MDC|1.3.1.202834.4|active||||||F
OBX|5|ST|68168^MDC_ATTR_ALARM_PRIORITY^MDC|1.3.1.202834.6|PM||||||F
OBX|6|ST|68169^MDC_ATTR_ALERT_TYPE^MDC|1.3.1.202834.7|ST||||||F
```

**Expected behaviour**
able to cast the ORU_R40 message.

**Screenshots**

**Sample HL7**
If applicable, add a sample hl7 message to help highlight your problem.

**Environmental Details (please complete the following information):**
 - OS: [e.g. Windows Server 2019, Ubuntu 18.04]
 - Target Framework [e.g. net461, netstandard2.0, netcoreapp3.1, net5.0] 
 - Version [e.g. 2.5.0.6]
 - HL7 Version [e.g. 2.4]

**Additional context**

**Comment by milkshakeuk** [comment]
@alberk8 `ORU_R40` does exist but only for the hl7 specification 2.8 and 2.8.1 as I don't think existed in prior hl7 specifications  and your message is using the 2.6 as the hl7 specification. It does not have its own class, instead the hl7 is parsed into a shared model which is the `ORU_R01` class.

Could you try that and let me know how it goes.

**Comment by milkshakeuk** [comment]
@alberk8 I'm going to close this ticket.

If you still think this is still an actual issue please feel free to re-open this and provide some additional info.

**Comment by alberk8** [comment]
> @alberk8 I'm going to close this ticket.
> 
> If you still think this is still an actual issue please feel free to re-open this and provide some additional info.

So sorry for the delay as I did not check back,    I think it is a problem with the originating HL7 source, where they use version 2.6 but with ORU_R40.  By the way, the message comes from MindRay.
