### ISSUE TITLE
.Net Language incompatibility

### ISSUE THREAD

**Issue by kalatchev** [nHapiNET/nHapi#233]
**Description**
In class `NHapi.Base.Model.ExtraComponents` there is a **.net language incompatibility** because there are two methods (`GetComponent` and `NumComponents`) that have duplicates with a different casing, which works only in C#, but not in a case-insensitive languages such as VB.NET. Example: `getComponent` and `GetComponent`. These two methods are uninvokable through VB.NET and generally have to be considered as a non-CLS compliant. Moreover, lower-case variants are marked as deprecated, so IMHO they should be simply removed.

**Environmental Details:**
 - OS: Windows 10 Pro x64
 - Target Framework: net46
 - Version: 3.0.4
 - HL7 Version: Any

**Additional details**
I tried to invoke them with `CallByName(obj1, "GetComponent", CallType.Method, 1)` but even that doesn't work and I'm getting `Exception thrown: 'System.Reflection.AmbiguousMatchException' in Microsoft.VisualBasic.dll`.

I searched over the code, and issue `SA1300` is found on numerous places, and all they will have the same issue.

**Comment by kalatchev** [comment]
Thank you @milkshakeuk !

Your suggestion works just fine. The only modification I did is

`
Dim methodInfo = GetType(ExtraComponents).GetMethods().FirstOrDefault(Function(m) m.Name = "GetComponent")
`

since string comparison is case sensitive and `Function(m) m.Name = "GetComponent"` returns correct `MethodInfo`, there is no need to check for attributes, at least in this given situation.

Once again, thanks!

**Comment by milkshakeuk** [comment]
@kalatchev no problem, glad it worked for you.
