### ISSUE TITLE
receiving arabic text in HL7 message

### ISSUE THREAD

**Issue by Bodda-Elmisry** [nHapiNET/nHapi#255]
When receiving HL7 message contains arabic characters HL7 receive them as '????'

**Comment by milkshakeuk** [comment]
@Bodda-Elmisry could you provide more details please perhaps some example messages etc.

**Comment by milkshakeuk** [comment]
@Bodda-Elmisry did u sort your issue or do u have any example messages and sample code?

**Comment by milkshakeuk** [comment]
@Bodda-Elmisry im closing this for now, if this is still an issue please feel free to re-open with some sample messages and example code, thank you.
