### ISSUE TITLE
Cannot get ODS segment using terser, when I write a full path 

### ISSUE THREAD

**Issue by zigh-code** [nHapiNET/nHapi#319]
**Describe the bug**

Cannot get ODS segments in ORDER_DIET  group using terser, when I write a full path 

**Screenshots**
![image](https://user-images.githubusercontent.com/12752657/179924359-8f26af7a-4169-4f31-a7a3-7557dc30acca.png)

**Sample HL7**
/.ORDER_DIET(0)/DIET/ODS(0)-1

**Comment by milkshakeuk** [comment]
@zigh-code do you could you provide some more information? sample hl7, hl7v2 version, perhaps even a unit test or code example?

**Comment by zigh-code** [comment]
I'm using the last version of the package.
The version of Hl7 in my case is 2.5 (string data), 

![image](https://user-images.githubusercontent.com/12752657/180006769-2515f75e-ab9a-44c9-b35e-801117720323.png)
If I try for the TQ1 segment, it work

![image](https://user-images.githubusercontent.com/12752657/180007092-11eef7bf-77e7-4f1e-9cb5-7c0b6cdc5b56.png)
But when I try with ODS, there is an issue



Data Test:
 string omdText = "MSH|^~\\&|EDITE|TEST|TEST|TEST|20210519141200||OMD^O03^OMD_O03|202105191412001|P|2.5|||||FRA|8859/1\r" +
        "PID|1|465 306 5961||407623|Wood^Patrick^^^MR||19700101|1|||High Street^^Oxford^^Ox1 4DP~George St ^^Oxford^^Ox1 5AP|||||||\r" +
        "ORC|NW|1254481^EDITEUR|||||^^^20210519143000||20210519143000|611014333^PRESCRIPTEUR^TEST1^^^^^^EDITEUR^^^^ADELI~10002129790^PRESCRIPTEUR^TEST1 ^^^^^^EDITEUR ^^^^RPPS~1027^PRESCRIPTEUR^TEST1^^^^^^EDITEUR^^^^EI||||||||||||||||||||\r" +
        "TQ1|1||||||20210519143000|\r" +
        "ODS|R||SANSSEL^Sans sel^EDITEUR|";

**Comment by milkshakeuk** [comment]
@zigh-code thanks for the extra info, will take a look when I can.

**Comment by milkshakeuk** [comment]
@zigh-code sorry for the long delay in getting back to you, I think I found the issue, its related to how java and dotnet use regex slightly differently so basically a bug in the port.

I will hopefully have a PR for this in the coming days.

**Comment by milkshakeuk** [comment]
@zigh-code I have put up a PR to fix this and included a unit test to prove it works.

**Comment by milkshakeuk** [comment]
@zigh-code this fix will go out in the next release, hoping to get a few more changes in first though

**Comment by milkshakeuk** [comment]
@zigh-code this change is in the latest `3.2.0` version.
