### ISSUE TITLE
Missing Insert functionality for repeatible fields

### ISSUE THREAD

**Issue by lechuckcaptain** [nHapiNET/nHapi#34]
It's hard to create a message from scratch using nHapi, and it's almost impossible when it's necessary to fill repeatible fields (e.g. PID-3).

I managed to go on using the Terser like this (it seems that the repetition is created when necessary, but it's needed the strange repetition PID-3-1 and PID-3(1)-1).

terser.Set("/PATIENT/PID-3-1", "a");
terser.Set("/PATIENT/PID-3(1)-1", "bb");
terser.Set("/PATIENT/PID-3(2)-1", "ccc");
terser.Set("/PATIENT/PID-3(3)-1", "dddd");
terser.Set("/PATIENT/PID-3(4)-1", "eeeee");

The HAPI library already provides a better and easier set functionality:

http://hl7api.sourceforge.net/v231/apidocs/ca/uhn/hl7v2/model/v231/segment/PID.html

**Comment by milkshakeuk** [comment]
@lechuckcaptain I don't suppose you could update your link, it's out of date by now... sorry.
Also you point to how this is done in hapi?

**Comment by lechuckcaptain** [comment]
Sorry @milkshakeuk, don't have anymore the setup to answer your question. Maybe if we are lucky enough @GiorgioFGambini can tell us if it's still an issue or not.

**Comment by milkshakeuk** [comment]
@lechuckcaptain looks like the new url is https://hapifhir.github.io/hapi-hl7v2/v231/apidocs/ca/uhn/hl7v2/model/v231/segment/PID.html

**Comment by milkshakeuk** [comment]
@lechuckcaptain you can technically add repetitions without the insert functionality:

If you call `GetPatientIDInternalID` and the repetition doesn't exist it will create it and return it to you as long as you don't use a repetition greater than the number of current repetitions.

If you need to know how many repetitions there currently are you can call `GetTotalFieldRepetitionsUsed()`
```csharp
var a01 = new ADT_A01();
var id1 = a01.PID.GetPatientIDInternalID(0);
var id2 = a01.PID.GetPatientIDInternalID(1);
var id3 = a01.PID.GetPatientIDInternalID(2);

id1.ID.Value = "123456";
id2.ID.Value = "000000";
id3.ID.Value = "987654";
```
