### ISSUE TITLE
nHapi returns error for valid HL7 files while doing validation concurrently

### ISSUE THREAD

**Issue by v-nmadwani** [nHapiNET/nHapi#393]
### Discussed in https://github.com/nHapiNET/nHapi/discussions/392

<div type='discussions-op-text'>

<sup>Originally posted by **v-nmadwani** December  8, 2022</sup>
We are using nHapi to validate batch of 1000 HL7 files (want to use it for much more files).
We are using Parallel.ForEachAsync loop with degree of parallelism set to 250.
For some of the valid HL7 files we receive errors as below:
1. An item with the same key has already been added. Key: ^~\&
2. Index was outside the bounds of the array.Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array
3. Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.

Please suggest on this, we are kind of blocked on this.

Thanks
</div>

**Comment by milkshakeuk** [comment]
Hi @v-nmadwani could you please provide more details, such as version of nhapi version of dotnet etc etc more logs.

**Comment by v-nmadwani** [comment]
Hi @milkshakeuk 
We are using nhapi version 2.0.3 and .net 6.0

**Comment by milkshakeuk** [comment]
@v-nmadwani nhapi `2.0.3` is very old and doesn't support `net6.0` are u sure this is the version? Could you perhaps provide a sample test project so it can be replicated?

**Comment by milkshakeuk** [comment]
@v-nmadwani any update on this?

**Comment by milkshakeuk** [comment]
@v-nmadwani if you are not able to provide more information / samples etc then I will have to close this issue.

**Comment by milkshakeuk** [comment]
@v-nmadwani I'm closing this ticket for now, if you feel it's still an issue please re-open with the additional information.
