### ISSUE TITLE
Exception adding an escaped string as field to Segment

### ISSUE THREAD

**Issue by manosg80** [nHapiNET/nHapi#414]
**Describe the bug**
I was trying to find out why it throws an exception when adding a particular field to header so  I broke down the string to p1 and p2.

**To Reproduce**
Just run the following code:
```csharp
 Segment mshSegment = new Segment("MSH", new HL7Encoding());
            mshSegment.AddNewField("|", 1);
            string p1 = @"^~\";
            string p2 = @"&";
            string p3 = p1 + p2;
            mshSegment.AddNewField(p3, 2); 

```

**Expected behaviour**
Should add the field

**Screenshots**
![image](https://user-images.githubusercontent.com/4488159/219122562-f27a482c-c866-4ccf-acf1-88ee47bcc836.png)

**Sample HL7**
If applicable, add a sample hl7 message to help highlight your problem.

**Environmental Details (please complete the following information):**

- OS: Windows 10 pro
- Target Framework  .NET 4.7.2
- Version [e.g. 2.5.0.6]  3.22
- HL7 Version [e.g. 2.4] 2.3

**Additional context**

**Comment by manosg80** [comment]
Don't know if this is HL7 dotnetcore issue or NHAPI

**Comment by milkshakeuk** [comment]
@manosg80 I've never seen that technique for creating segments before, have you tried newing up a MSH segment instead?

I'm not saying it's not an issue just never seen it done that way before.

Maybe this will help.
https://saravanansubramanian.com/hl72xnhapicreatemessage/

**Comment by manosg80** [comment]
Yes, actually using the MSH Segment was how I bypassed the issue. I had found this approach in a couple of tutorials with a more 'loose' approach as to what MSH fields should be present. I guess the '\' character is used for delimiting and hence can't exist in a field - at least that's what I think.

**Comment by milkshakeuk** [comment]
@manosg80 The code samples provided seem to be from HL7 dotnetcore not nhapi.

**Comment by manosg80** [comment]
You are right, hence my previous comment that I might be knocking the wrong door. Apologies!

**Comment by milkshakeuk** [comment]
@manosg80 as this is not an nhapi issue can you close this?

**Comment by manosg80** [comment]
Done.
