### ISSUE TITLE
support for Fast Healthcare Interoperability Resources (FHIR)

### ISSUE THREAD

**Issue by AlexFJaxFL** [nHapiNET/nHapi#433]
would your software be able to handle https://rhapsody.health/use-cases/fhir/ 
https://rhapsody.health/blog/fhir-vs-hl7-explained/

**Comment by AlexFJaxFL** [comment]
nope, no specific case (at the moment), 
we are trying to implement home grown solution and your link seems very helpful indeed

best regards!

**Comment by milkshakeuk** [comment]
@AlexFJaxFL I am closing this for now, feel free to re-open if you think of something specific.
