### ISSUE TITLE
Field OBX-5 in V21 is defined as ST and not defined as type Varies

### ISSUE THREAD

**Issue by 0x4AMiller** [nHapiNET/nHapi#45]
Which is causing invalid cast exception on line # 184 in NHapi.Base.Model.Varies 

in fixOBX5 method...
foreach (IType repetition in segment.GetField(5))
{
    Varies v = (Varies) repetition;                               <--- Invalid cast exception
        ...
}

**Comment by milkshakeuk** [comment]
@0x4AMiller Hi thanks for this, I also discovered this whilst writing unit tests for another issue #133 so will fix this in the same PR
