### ISSUE TITLE
getting exceptions trying to compile vb.net project against nhapi 3.2 (in c# it probably would have been ok but we are using vb.net)

### ISSUE THREAD

**Issue by AlexFJaxFL** [nHapiNET/nHapi#547]
getting the following exceptions trying to compile vb.net project: 

error BC31429: 'addNonstandardSegment' is ambiguous because multiple kinds of members with this name exist in class 'AbstractGroup'. (and i do see kind of duplicate definitions there   

      Public Overridable Function AddNonstandardSegment(name As String, index As Integer) As String
      Public Overridable Function AddNonstandardSegment(name As String) As String
      Public Overridable Function addNonstandardSegment(name As String) As String
      
      in c# this probably would have worked but we are using vb.net 

getSegment' is ambiguous because multiple kinds of members with this name exist in class 'Terser'. (and i do see duplicate definitions             Public Overridable Function getSegment(segSpec As String) As ISegment
Public Overridable Function GetSegment(segSpec As String) As ISegment

this probably would have worked in c# but we are using vb.net)

error BC30456: 'InsuredSIDNumber' is not a member of 'IN1'.

warning BC40000: 'Public Overloads ReadOnly Property InsuranceCompanyID As CX' is obsolete: 'Use 'GetInsuranceCompanyID(int rep)' instead.'. <= this one looks clear to me

 warning BC40000: 'Public Overloads ReadOnly Property InsuranceCompanyName As XON' is obsolete: 'Use 'GetInsuranceCompanyName(int rep)' instead.'. <= this one looks clear to me

**Environmental Details (please complete the following information):**

- OS: Windows 10
- Target Framework [.net 4.6.1]
- Version [e.g. 3.2]
- HL7 Version [n/a]

**Comment by milkshakeuk** [comment]
@AlexFJaxFL you might want to look at #233

**Comment by AlexFJaxFL** [comment]
ok, will try this approach hopefully sometime this week and will provide an update here

**Comment by AlexFJaxFL** [comment]
ok, approach proposed in issue 233 (to use reflection) worked for me very well!

**Comment by AlexFJaxFL** [comment]
issue resolved!
