### ISSUE TITLE
Value cannot be null. Parameter name: type

### ISSUE THREAD

**Issue by GhassanF** [nHapiNET/nHapi#57]
Hi,

I am getting this error whenever i tried to parse a message for any version that ends with ".1" (2.3.1, 2.5.1, 2.7.1). if i manually remove the ".1" from the message version  it works normally. 

Code:
`PipeParser parse = new PipeParser();
IMessage message = parse.Parse(dataReceived);`

Kindly note that i am using C# and nHapi 2.5.0.5

Thank you in advance.

**Comment by milkshakeuk** [comment]
@GhassanF I'm closing this for now as there is not enough information to replicate.
If it's still an issue, please re-open with appropriate sample HL7 messages.
