### ISSUE TITLE
.NET Core support?

### ISSUE THREAD

**Issue by cdroulers** [nHapiNET/nHapi#61]
Are there any plans to modify the code to support .NET Core? I've opened the Portability Analysis Report in Visual Studio and it seems there's a lot of things to check, but I don't know if it's easy to do or not. Anyone more familiar with this code base care to comment?

[nHapi.Base-PortabilityAnalysis.pdf](https://github.com/duaneedwards/nHapi/files/493867/nHapi.Base-PortabilityAnalysis.pdf)

I've found that a basic migration would get rid of all "System.Configuration" problems since they seem to be related to the settings file.

There's also `OleDb` stuff and `Xml` stuff. The rest seems supported or very straight forward to fix.

The library looks great!

**Comment by jaime-olivares** [comment]
.Net Core and specially .Net Standard are the future of .Net. This requirement is a must.

**Comment by atesoglu** [comment]
+1

**Comment by atesoglu** [comment]
This issue has been opened nearly a year ago and there has been nothing, not a single word yet?
I think this is a shame.

**Comment by truthbeliever** [comment]
Any news?

**Comment by jaime-olivares** [comment]
Due to the lack of .net core support, we created our own lightweight library: https://github.com/Efferent-Health/HL7-dotnetcore

**Comment by Usualdosage** [comment]
Solution updated to netstandard2.0.

**Comment by milkshakeuk** [comment]
Not been merged yet... but soon :D
