### ISSUE TITLE
OBX|ID null ref exception in fixOBX-5

### ISSUE THREAD

**Issue by rdurham285** [nHapiNET/nHapi#62]
The PipeParser is blowing up with any OBX segment with type of ID with a value in OBX-5.

Segment: `OBX|3|ID|59781-5^dose validity^LN|1|Y||||||F|||20151031`
Stack: `System.NullReferenceException trying to set data type of OBX-5`
Code: `var pParser = new PipeParser(); var msg = pParser.Parse(rawMessage);`

Thanks

**Comment by qtuan** [comment]
Hi, is there a known solution for this? Thanks!
