### ISSUE TITLE
Mapping of ORM_O01 on NHapi.Model.V23.EventMap.properties

### ISSUE THREAD

**Issue by josephrodriguez** [nHapiNET/nHapi#67]
On commit 80ae7b7c7fd433272fd9a00cec01c6a8b6194e4c the map if fixed with:

ORM_O01 ORM_O01	
OMD_O01 ORM_O01	
OMN_O01 ORM_O01	
OMS_O01 ORM_O01	
RDO_O01 ORM_O01

but on commit 0ea641f5ef273ec90536cb11f38f648cd97ab363 this change is roll backed. Actually parse an ORM_O01 return a GenericMessage.

**Comment by milkshakeuk** [comment]
This looks to be the same issue as #35.
