### ISSUE TITLE
Custom Z Segment example ?

### ISSUE THREAD

**Issue by hiravebapu** [nHapiNET/nHapi#76]
Hi,
How does NHapiTools support to

Add non standard z segment
Add custom properties to newly added z segment
can you provide some example ?

**Comment by trzewior** [comment]
Bump.

**Comment by Usualdosage** [comment]
It doesn't.

`
case "\\Z":
   // We don't support this.
   //if (hex.All(c => HexDigits.Contains(char.ToUpper(c))))
   //{
   //    encodeCharacter = false;
   //    isEncodingSpecialCharacterSequence = true;
   //}
   break;
`

Ref: Escape.cs line 164
