### ISSUE TITLE
Getting NHapi.Base.Model.GenericMessage.V25 instead of NHapi.Model.V25.Message.OUL_R22

### ISSUE THREAD

**Issue by GertBroekhaar** [nHapiNET/nHapi#77]
Hi there,

I'm expecting the **Parse**-method below to return an object of type **NHapi.Model.V25.Message.OUL_R22** but it returns **NHapi.Base.Model.GenericMessage.V25** so the next cast to **OUL_R22** is giving an **InvalidCastException**. Can you please provide some help?

Thanks very much,
Gert

string message = @"MSH|^~\&|^980^test|||[???]^[CODE RIVM]^|20161018172259||OUL^R22^OUL_R22|123456789|T|2.5|||NE|NE||UNICODE 

UTF-8|||^^2.16.840.1.113883.2.4.3.11.60.25.10.38^ISO
                PID|||123456789^^^NI||TestTest^T.^E.S.T.||19760101|M|||Laan 123^^Ergens^^1234ZZ^NL 
                PV1||N|^^^X2&x3^^RIVM-K|||||||01.045|||||||||||||||||||||||||||||ZKH|||||20161004 
                SPM||&&1|&&M1234567|78014005^Urine^SNM|||225271002^Collection of mid-stream specimen of urine^SNM|431938005^ 

Structure of urinary tract proper^SNM|||||||||20161006|20161007 
                OBR||1610070657||6463-4^Bacteria identified in Unspecified specimen by Culture^LN|||||||||||||||||||||||||||S 
                ORC|NW|1610070657 
                OBX||CE|6463-4^Bacteria identified in Unspecified specimen by Culture^LN||56415008^Klebsiella 

pneumoniae^SNM||||||F|||20161007";

                PipeParser parser = new NHapi.Base.Parser.PipeParser();
                IMessage messageObject = parser.Parse(message);
                OUL_R22 r22 = (OUL_R22)messageObject;

**Comment by milkshakeuk** [comment]
This seems to be working in the most recent version [v3.0.0-preview.2](https://github.com/nHapiNET/nHapi/releases/tag/v3.0.0-preview.2).

```csharp
[Test]
public void Test()
{
    var input =
        @"MSH|^~\&|^980^test|||[???]^[CODE RIVM]^|20161018172259||OUL^R22^OUL_R22|123456789|T|2.5|||NE|NE||UNICODE UTF-8|||^^2.16.840.1.113883.2.4.3.11.60.25.10.38^ISO
PID|||123456789^^^NI||TestTest^T.^E.S.T.||19760101|M|||Laan 123^^Ergens^^1234ZZ^NL 
PV1||N|^^^X2&x3^^RIVM-K|||||||01.045|||||||||||||||||||||||||||||ZKH|||||20161004 
SPM||&&1|&&M1234567|78014005^Urine^SNM|||225271002^Collection of mid-stream specimen of urine^SNM|431938005^Structure of urinary tract proper^SNM|||||||||20161006|20161007 
OBR||1610070657||6463-4^Bacteria identified in Unspecified specimen by Culture^LN|||||||||||||||||||||||||||S 
ORC|NW|1610070657 
OBX||CE|6463-4^Bacteria identified in Unspecified specimen by Culture^LN||56415008^Klebsiella pneumoniae^SNM||||||F|||20161007";

    var parser = new PipeParser();
    var message = parser.Parse(input);

    Assert.IsNotAssignableFrom<GenericMessage>(message);
    Assert.IsAssignableFrom<OUL_R22>(message);
}
```

I'll close this for now, if you think that this is not fixed, please re-open this ticket.
