### ISSUE TITLE
HAPI FHIR support

### ISSUE THREAD

**Issue by hiravebapu** [nHapiNET/nHapi#78]
Any plans for support HL7 FHIR in nHapi

**Comment by nityan** [comment]
Hello, 
For HL7 FHIR support, please check here:

https://github.com/ewoutkramer/fhir-net-api

Thanks,
Nityan

**Comment by hishamrashdan** [comment]
Hello,
I want to use this library for a real production project, but I want to be sure is this library still supported by its developers if any new bugs founded ?!
Is it safe to use?  I want to use the hl7 2.4 version of the library.

**Comment by Usualdosage** [comment]
This project is maintained and will support 2.4.
