### ISSUE TITLE
HL7 2.3 ORM^O01 Parsed as Generic V23 message

### ISSUE THREAD

**Issue by jsdratm** [nHapiNET/nHapi#79]
Affected Version: 2.5.0.6

I was using this test message and instead of parsing it to a ORM_O01 object it is parsing it into a generic V23 object.  If I change the version to 2.2 or 2.4 it is parsed correctly, so the issue appears isolated to v2.3.

MSH|^~\&|HIS|MedCenter|LIS|MedCenter|20060307110114||ORM^O01|MSGID20060307110114|P|2.3
PID|||12001||Jones^John^^^Mr.||19670824|M|||123 West St.^^Denver^CO^80020^USA|||||||
PV1||O|OP^PAREG^||||2342^Jones^Bob|||OP|||||||||2|||||||||||||||||||||||||20060307110111|
ORC|NW|20060307110114
OBR|1|20060307110114||003038^Urinalysis^L|||20060307110114

**Comment by milkshakeuk** [comment]
This seems to be working in the most recent version [v3.0.0-preview.2](https://github.com/nHapiNET/nHapi/releases/tag/v3.0.0-preview.2).

```csharp
[Test]
public void Test()
{
    var input =
        @"MSH|^~\&|HIS|MedCenter|LIS|MedCenter|20060307110114||ORM^O01|MSGID20060307110114|P|2.3
PID|||12001||Jones^John^^^Mr.||19670824|M|||123 West St.^^Denver^CO^80020^USA|||||||
PV1||O|OP^PAREG^||||2342^Jones^Bob|||OP|||||||||2|||||||||||||||||||||||||20060307110111|
ORC|NW|20060307110114
OBR|1|20060307110114||003038^Urinalysis^L|||20060307110114";

    var parser = new PipeParser();
    var message = parser.Parse(input);

    Assert.IsNotAssignableFrom<GenericMessage>(message);
    Assert.IsAssignableFrom<ORM_O01>(message);
}
```

I'll close this for now, if you think that this is not fixed please re-open this ticket.
