### ISSUE TITLE
HL7 2.7 Fails to Parse ORM^O01

### ISSUE THREAD

**Issue by jsdratm** [nHapiNET/nHapi#82]
Error: Can't find message class in current package list: ORM_O01

MSH|^~\&|HIS|MedCenter|LIS|MedCenter|20060307110114||ORM^O01|MSGID20060307110114|P|2.7
PID|||12001||Jones^John^^^Mr.||19670824|M|||123 West St.^^Denver^CO^80020^USA|||||||
PV1||O|OP^PAREG^||||2342^Jones^Bob|||OP|||||||||2|||||||||||||||||||||||||20060307110111|
ORC|NW|20060307110114
OBR|1|20060307110114||003038^Urinalysis^L|||20060307110114

**Comment by milkshakeuk** [comment]
Message Type `ORM_O01` in HL& Spec V2.7, which is why there is no message class for it.
