### ISSUE TITLE
HL7 2.8 Fails to parse ORM^O01

### ISSUE THREAD

**Issue by jsdratm** [nHapiNET/nHapi#83]
Error: Can't find message class in current package list: ORM_O01

Message:
MSH|^~\&|HIS|MedCenter|LIS|MedCenter|20060307110114||ORM^O01|MSGID20060307110114|P|2.8
PID|||12001||Jones^John^^^Mr.||19670824|M|||123 West St.^^Denver^CO^80020^USA|||||||
PV1||O|OP^PAREG^||||2342^Jones^Bob|||OP|||||||||2|||||||||||||||||||||||||20060307110111|
ORC|NW|20060307110114
OBR|1|20060307110114||003038^Urinalysis^L|||20060307110114

**Comment by garykb** [comment]
Last version with support for ORM^O01 in nHapi is V2.6.

**Comment by jsdratm** [comment]
Gary,

Do you know if there is a reason why, or is it just something that hasn't been implemented yet?

**Comment by garykb** [comment]
The latest spec I have from HL7.org. which is version 2.5.1 states that this message has been deprecated and recommends replacements for later versions of HL7.

**Comment by milkshakeuk** [comment]
Message Type `ORM_O01` in HL& Spec V2.8, which is why there is no message class for it.
