### ISSUE TITLE
Parse Result between 2.5.0.5 and 2.5.0.6

### ISSUE THREAD

**Issue by nasu38yen** [nHapiNET/nHapi#89]
For example, the parsing result of the OML -O33
In 2.5.0.5, although the PID segment is also stored
In 2.5.0.6, the PID segment was not stored
Why is this?

**Comment by milkshakeuk** [comment]
@nasu38yen could you provide a sample HL7 message for testing this please?

**Comment by milkshakeuk** [comment]
@nasu38yen I'm closing this for now as there is not enough information to replicate.
If it's still an issue, please re-open with appropriate sample HL7 messages.
