### ISSUE TITLE
HL7 2.4 ORU_R01 why only supports single ORC,OBR,OBX

### ISSUE THREAD

**Issue by 15953327207** [nHapiNET/nHapi#90]
MSH|^~\&|BioxunSystem|1.0.2|HIS||201709071602||ORU^R01|7fe8ee28-6e95-49fd-9885-ce6628aea118|^P|2.4|||||CHN|UTF-8
ORC|1|9997d257-25b4-4b54-8e41-9701faee25ca|||||^^^201709071602|||1
OBR|1|=0160217705896||AS|||201709071449|201709071516|||||||BLD^^^^^^P|||||||||O|||^^^^^R
OBX|1|ST|AS||Negative||||||F|201709071449||201709071516|1
ORC|2|4b6bfd70-ce6e-4591-be79-fc53ba31c5eb|||||^^^201709071602|||1
OBR|1|=0160217705896||ABOR|||201709071454|201709071503|||||||BLD^^^^^^P|||||||||O|||^^^^^R
OBX|1|ST|ABOR||B||||||F|201709071454||201709071503|1
ORC|3|c53ccfdc-7a79-4078-b2e5-34f1bcc950a5|||||^^^201709071602|||1
OBR|1|=0160217903311||AS|||201709071449|201709071515|||||||BLD^^^^^^P|||||||||O|||^^^^^R
OBX|1|ST|AS||Negative||||||F|201709071449||201709071515|1

why only last result after parser?
PipeParser parser = new PipeParser();
hl7Message = parser.Parse(message);
ORU_R01 opr = (ORU_R01)hl7Message;
int resultNums = opr.PATIENT_RESULTRepetitionsUsed;
why is value of the PATIENT_RESULTRepetitionsUsed  1?

**Comment by milkshakeuk** [comment]
It doesn't, it supports multiple `ORDER_OBSERVATION` groups which is groups of `ORC`, `OBR`, `OBX`.

![image](https://user-images.githubusercontent.com/1087376/114375228-5e94eb80-9b7c-11eb-9451-0a2823922d54.png)

What you have above is multiple ORDER_OBSERVATIONS.

```csharp
[Test]
public void Test()
{
    var input =
        @"MSH|^~\&|BioxunSystem|1.0.2|HIS||201709071602||ORU^R01|7fe8ee28-6e95-49fd-9885-ce6628aea118|^P|2.4|||||CHN|UTF-8
ORC|1|9997d257-25b4-4b54-8e41-9701faee25ca|||||^^^201709071602|||1
OBR|1|=0160217705896||AS|||201709071449|201709071516|||||||BLD^^^^^^P|||||||||O|||^^^^^R
OBX|1|ST|AS||Negative||||||F|201709071449||201709071516|1
ORC|2|4b6bfd70-ce6e-4591-be79-fc53ba31c5eb|||||^^^201709071602|||1
OBR|1|=0160217705896||ABOR|||201709071454|201709071503|||||||BLD^^^^^^P|||||||||O|||^^^^^R
OBX|1|ST|ABOR||B||||||F|201709071454||201709071503|1
ORC|3|c53ccfdc-7a79-4078-b2e5-34f1bcc950a5|||||^^^201709071602|||1
OBR|1|=0160217903311||AS|||201709071449|201709071515|||||||BLD^^^^^^P|||||||||O|||^^^^^R
OBX|1|ST|AS||Negative||||||F|201709071449||201709071515|1";

    var parser = new PipeParser();
    var message = parser.Parse(input);
    var oru = (ORU_R01)message;

    var repetitions = oru.GetPATIENT_RESULT().ORDER_OBSERVATIONRepetitionsUsed;

    Assert.AreEqual(3, repetitions);
}
```
