### ISSUE TITLE
Failed to parse ORC-10 repetitions in ORM^O01 for version 2.3

### ISSUE THREAD

**Issue by Telexy-zz** [nHapiNET/nHapi#91]
Seam like a bug, working fine for all other versions, except 2.3. Parser rejects multiple ORC-10 repetitions. Here is the message for reproduce.

MSH|^~\&|CERNER|C|MEDCON||20171011142204||ORM^O01|Q5541223210T4287161621^M197||2.3||||||8859/1
PID|1|10950522^^^C^MRN|100010552^^^^MRN~10950522^^^C^MRN~10950522^^^^MRN~10950522^^^^MRN~10950522^^^^MRN~10950522^^^^MRN~10950522^^^^MRN~100010552~9905813^^^^MRN|18502202~9905813~10950522|BALLOON^RED^^^^^Current||19820914|F|||914 RED RD^^CHARLOTTE^NC^28231^US~^^^""^""^""^^^""||7045559141^H^""|^^""|E||""|6400079383^^^^FIN|91419822|||||""|0|""|""|""||""
PV1|1|E|CDIA^^^C^^^C||||6712^GIBBS^MICHAEL^A^^MD^^^^^^^^""|||EMD|CDIA|""|""||""|""|549^TEST^CMC^MD^^^^^STAR^^^^STAR^""|ER||||||||||||||||||""|""|""|C||A|||20170516095000
ORC|NW|13411937043^HNAM_ORDERID|||CD:2550||||20171011142137|9501334475^TEST^RESIDENT^^^^^^^^^^^""~4672^TEST^RESIDENT^^^^^^^^^^^""~6714546903001^TEST^RESIDENT^^^^^^^^^^^""||9501334475^TEST^RESIDENT^^^^^^^^^^^""|""||20171011142203|||^Written|9501334475^TEST^RESIDENT^^^^^^^^^^^""~4672^TEST^RESIDENT^^^^^^^^^^^""~6714546903001^TEST^RESIDENT^^^^^^^^^^^""
OBR|1|13411937043^HNAM_ORDERID||AAA^ED AAA US|||||||||||Rad Type&Rad Type|9501334475^TEST^RESIDENT^^^^^^^^^^^""||||||20171011142203||US|||1^ONCE^0^20171011142100^^S

Thanks

**Comment by milkshakeuk** [comment]
From what I understand about `ORC-10` in HL7 V23 it is [not repeatable](https://hl7-definition.caristix.com/v2/HL7v2.3/Fields/ORC.10).

**Comment by jakubsuchybio** [comment]
I understand that the same as you, non-repeatable.
