### ISSUE TITLE
OBX/NTE Segment not getting Parsed

### ISSUE THREAD

**Issue by mettlus** [nHapiNET/nHapi#93]
I have a repeating OBX/NTE Segment
unfortunately when I parse it via the terser object I dont get values in the NTE Segment

OBX|1
NTE|1|2....
OBX|2
NTE|2|322...
parser.Get("/OBSERVATION(0)/NTE1-1"); returns NULL

**Comment by Usualdosage** [comment]
Valid issue. NTE segments are being added but values are always null. Will address.

**Comment by milkshakeuk** [comment]
@mettlus could you provide a sample HL7 message and tell us what version of NHapi this issue is for and what version of hl7?

Cheers.

**Comment by milkshakeuk** [comment]
@mettlus I'm closing this for now as there is not enough information provided to replicate.
If it's still an issue, please re-open with appropriate example HL7 messages.
