### ISSUE TITLE
Remove repetition from segment

### ISSUE THREAD

**Issue by yoliva** [nHapiNET/nHapi#94]
What I'm trying to achieve is to remove all the repetitions from `OM5-2`. That can be achieved using NHAPI?

`OM5|83|123-4^someText^LN^1001^someText^99CTX~133-4^someText1^LN^1008^someText1^99CTX~223-4^someText2^LN^1010^someText2^99CTX`

**Comment by Usualdosage** [comment]
You can use NHapi to find the total repetitions used as well as the instances of OM5 within a message. OM5 can contain repetitions of CE, but the message you provided appears to contain multiple CE elements in the same field. Per the  spec, I don't think that is allowed. 

> **8.8.12.2 OM5-2 Tests/Observations Included Within An Ordered Test Battery (CE) 00655**
> _Components_: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)>
