### ISSUE TITLE
Message escaping still isn't functioning properly on all UNC strings

### ISSUE THREAD

**Issue by nkm8** [nHapiNET/nHapi#95]
Extension of https://github.com/duaneedwards/nHapi/issues/44

If you have a UNC path, the `\\` sequence used to represent `\` in C# is parsed as `\e\` in the output generated by nHapi.

Example: `123\\456` is output as `123\e\456` after calling `PipeParser.Encode()`

Bonus: `\e\` is completely ignored by a separate HL7 parsing tool that is ingesting the output I am creating.

As a temporary work-around, I found that using `/` instead of `\` in the UNC path still allows C# to write the file/directory successfully.  That is, using `Path.AltDirectorySeparatorChar` instead of `Path.DirectorySeparatorChar`

**Comment by Usualdosage** [comment]
Closing this issue as there appears to be a practical method for accomplishing this using native .NET code. Thanks for the information, nkm8!
